//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKTXWindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occupancy
    {
        public int OccupancyID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<int> CycleMonths { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Student Student { get; set; }
    }
}
